server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9081
locations_csv: starbucks.csv
#radius for lookup, in meters
lookup_radius: 2000
#where to send sms
#notification_number: +1234567890
plivo_id: MAM2JMZGM2NZU4MJLLYT
plivo_token: MjQ2ZTI3M2FhNzJiODhjYWRkMmM3ZTA2ZGZjOWVh
plivo_number: 16623402368
